version: '3'

services:
  nest-app:
    image: jimeme/simulizer-back:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local